#!/bin/bash

# PHPStan
Api/vendor/bin/phpstan --configuration=Api/phpstan.neon --no-progress --memory-limit=1G

# PHPUnit
#Api/vendor/bin/phpunit .\tests\ --testdox --testsuite feature --colors=always --coverage-html coverage

exit 0